# Generated by Django 4.1.4 on 2022-12-23 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_comment_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='published_date',
        ),
    ]
